## default pipeline
# nodes:
# - input.visual:
#     source: https://storage.googleapis.com/peekingduck/videos/wave.mp4
# - model.posenet
# - draw.poses
# - output.screen

# Mango classification
nodes:
- input.visual:
   source: ./model_data/inspection
- custom_nodes.model.fruit_classifier
- output.csv_writer:
   stats_to_track: ["filename", "pred_label", "pred_score"]
   file_path: mango_predictions.csv
   logging_interval: 0