# # Mandatory configs
# # Receive bounding boxes and their respective labels as input. Replace with
# # other data types as required. List of built-in data types for PeekingDuck can
# # be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
# input: ["bboxes", "bbox_labels"]
# # Example:
# # Output `obj_attrs` for visualization with `draw.tag` node and `custom_key` for
# # use with other custom nodes. Replace as required.
# output: ["obj_attrs", "custom_key"]

# # Optional configs depending on node
# threshold: 0.5 # example

input: ["img"]
output: ["pred_label", "pred_score"]

weights_parent_dir: weights
class_label_map: {1: "rotten", 0: "fresh"}